server:
  port: 9001

spring:
  application:
    name: mini-test
  datasource:
    url: jdbc:postgresql://postgres:5432/healthdb
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always